[time]
disabled = false
format = "[ %T ]"
utc_time_offset = "local"
time_range = "10:00:00-19:00:00"

[nodejs]
symbol = "â¬¢ "

[character]
symbol = "âœ "
error_symbol = "âœ—"
use_symbol_for_status = true
style_success = "normal yellow"

[package]
symbol = "ğŸ "

